/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AmbassadorRouteImport } from './routes/ambassador'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AmbassadorRegisterRouteImport } from './routes/ambassador.register'

const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbassadorRoute = AmbassadorRouteImport.update({
  id: '/ambassador',
  path: '/ambassador',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbassadorRegisterRoute = AmbassadorRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AmbassadorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ambassador': typeof AmbassadorRouteWithChildren
  '/register': typeof RegisterRoute
  '/registration': typeof RegistrationRoute
  '/ambassador/register': typeof AmbassadorRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ambassador': typeof AmbassadorRouteWithChildren
  '/register': typeof RegisterRoute
  '/registration': typeof RegistrationRoute
  '/ambassador/register': typeof AmbassadorRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ambassador': typeof AmbassadorRouteWithChildren
  '/register': typeof RegisterRoute
  '/registration': typeof RegistrationRoute
  '/ambassador/register': typeof AmbassadorRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ambassador'
    | '/register'
    | '/registration'
    | '/ambassador/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ambassador'
    | '/register'
    | '/registration'
    | '/ambassador/register'
  id:
    | '__root__'
    | '/'
    | '/ambassador'
    | '/register'
    | '/registration'
    | '/ambassador/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmbassadorRoute: typeof AmbassadorRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  RegistrationRoute: typeof RegistrationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambassador': {
      id: '/ambassador'
      path: '/ambassador'
      fullPath: '/ambassador'
      preLoaderRoute: typeof AmbassadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambassador/register': {
      id: '/ambassador/register'
      path: '/register'
      fullPath: '/ambassador/register'
      preLoaderRoute: typeof AmbassadorRegisterRouteImport
      parentRoute: typeof AmbassadorRoute
    }
  }
}

interface AmbassadorRouteChildren {
  AmbassadorRegisterRoute: typeof AmbassadorRegisterRoute
}

const AmbassadorRouteChildren: AmbassadorRouteChildren = {
  AmbassadorRegisterRoute: AmbassadorRegisterRoute,
}

const AmbassadorRouteWithChildren = AmbassadorRoute._addFileChildren(
  AmbassadorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmbassadorRoute: AmbassadorRouteWithChildren,
  RegisterRoute: RegisterRoute,
  RegistrationRoute: RegistrationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
